\SweaveOpts{fig=T,echo=F}
\section{Qualitative output analysis}\label{QualAnal}
Most of the times, after applying the Latin Hypercube Sampling to an 
ecological model, it is possible to identify qualitatively different 
behaviours of the model, possibly clustered into separate regions. In this
section, we will focus on tools to identify the different regions.
\begin{verbatim}
TODO
Descrever o problema e tecnicas para resolve-lo.
ConvexHull?
\end{verbatim}
